timestamp_format = "%s"

[[panels]]

[[panels.lines]]
guard = "linear"
field = "x00"
style = "steps"
[[panels.lines]]
guard = "linear"
field = "x01"
style = "steps"
[[panels.lines]]
guard = "linear"
field = "x02"
style = "steps"
[[panels.lines]]
guard = "linear"
field = "x03"
style = "steps"
[[panels.lines]]
guard = "linear"
field = "x04"
style = "steps"
[[panels.lines]]
guard = "linear"
field = "x05"
style = "steps"
[[panels.lines]]
guard = "linear"
field = "x06"
style = "steps"
[[panels.lines]]
guard = "linear"
field = "x07"
style = "steps"
[[panels.lines]]
guard = "linear"
field = "x08"
style = "steps"
[[panels.lines]]
guard = "linear"
field = "x09"
style = "steps"
[[panels.lines]]
guard = "linear"
field = "x10"
style = "steps"


[[panels]]

[[panels.lines]]
guard = "linear"
field = "x00"
style = "lines-points"
[[panels.lines]]
guard = "linear"
field = "x01"
style = "lines-points"
[[panels.lines]]
guard = "linear"
field = "x02"
style = "lines-points"
[[panels.lines]]
guard = "linear"
field = "x03"
style = "lines-points"
[[panels.lines]]
guard = "linear"
field = "x04"
style = "lines-points"
[[panels.lines]]
guard = "linear"
field = "x05"
style = "lines-points"
[[panels.lines]]
guard = "linear"
field = "x06"
style = "lines-points"
[[panels.lines]]
guard = "linear"
field = "x07"
style = "lines-points"
[[panels.lines]]
guard = "linear"
field = "x08"
style = "lines-points"
[[panels.lines]]
guard = "linear"
field = "x09"
style = "lines-points"
[[panels.lines]]
guard = "linear"
field = "x10"
style = "lines-points"

[[panels]]

[[panels.lines]]
guard = "linear"
field = "x00"
style = "points"
[[panels.lines]]
guard = "linear"
field = "x01"
style = "points"
[[panels.lines]]
guard = "linear"
field = "x02"
style = "points"
[[panels.lines]]
guard = "linear"
field = "x03"
style = "points"
[[panels.lines]]
guard = "linear"
field = "x04"
style = "points"
[[panels.lines]]
guard = "linear"
field = "x05"
style = "points"
[[panels.lines]]
guard = "linear"
field = "x06"
style = "points"
[[panels.lines]]
guard = "linear"
field = "x07"
style = "points"
[[panels.lines]]
guard = "linear"
field = "x08"
style = "points"
[[panels.lines]]
guard = "linear"
field = "x09"
style = "points"
[[panels.lines]]
guard = "linear"
field = "x10"
style = "points"
