name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}    
    - name: Build
      run: cargo build --verbose
    - name: pwd
      run: pwd
    - name: ls
      run: ls -al
    - name: ls2
      run: ls -al some-playground/
    - name: Run tests
      run: cargo test --verbose
    - name: Install Clippy and Rustfmt
      run: |
        rustup component add clippy rustfmt
    - name: Run rustfmt
      run: cargo fmt --all -- --check
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings      
