name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install Clippy and Rustfmt
      run: |
        rustup component add clippy rustfmt
    - name: Run rustfmt
      run: cargo fmt --all -- --check
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings      
